### ISSUE TITLE
New complementary Tool 

### ISSUE THREAD

**Issue by Leci37** [sunnyswag/StockRL#12]
My name is Luis, I'm a big-data machine-learning developer, I'm a fan of your work, and I usually check your updates.

I am developer something more complementary and full

- testing with 30+- models
- threshold evaluation
- use 1k technical indicators
- method of best feature selection (8, 16, 32..) nice nice
- categorical target instead of continuous target variable powerful machine-learning libraries such as: Sklearn.RandomForest , Sklearn.GradientBoosting, XGBoost, Google TensorFlow and Google TensorFlow LSTM.

With the models trained with the selection of the best technical indicators, the tool is able to predict trading points (where to buy, where to sell) and send real-time alerts to Telegram or Mail. The points are calculated based on the learning of the correct trading points of the last 2 years (including the change to bear market after the rate hike).

I think it could be useful to you, to improve, I would like to share it with you, and if you are interested in improving and collaborating I am also willing, and if not file it in the box.

https://github.com/Leci37/LecTrade/tree/develop

**Comment by sunnyswag** [comment]
Thanks and Bye
