### ISSUE TITLE
关于 trainer 和 trader 有2个疑惑寻求解答，谢谢

### ISSUE THREAD

**Issue by ghyzx** [sunnyswag/StockRL#13]
@sunnyswag  感谢作者的辛勤工作，这个项目很顺利的在本地跑起来了（比FinRL的旅程顺畅太多，大大的赞），有2个疑惑寻求解答，谢谢。

1.为何train里面(model.learn) 用trade的env？
https://github.com/sunnyswag/StockRL/blob/main/learn/trainer.py   -->   line 52
![train](https://github.com/user-attachments/assets/c7cce92c-b30e-4ce5-8a2b-b4bc61abd5db)

2.trainer 和 trader 的主要职责和区别在哪些方面？
https://github.com/sunnyswag/StockRL/blob/main/learn/trainer.py
https://github.com/sunnyswag/StockRL/blob/main/learn/trader.py
 似乎从开始到 agent.get_model 这一步都是类似的，下一步 trainer 是 model.learn （学习？），trader 是 DRL_Agent.DRL_prediction （预测？）；
 从 config 里的配置猜想，trader 主要是做回测的（tester？）；
https://github.com/sunnyswag/StockRL/blob/main/utils/config.py  -->   line 9~11
![date](https://github.com/user-attachments/assets/27bed25f-04b8-4f8d-818e-20d79b245818)

**Comment by sunnyswag** [comment]
谢谢的支持，这个项目没有花时间维护了，所以回的比较慢
1. 那里传的是 eval_env，evaluate 的意思，用来评估验证的环境
2. 你的猜想是对的，训练集和测试集的区别(大概这么个意思吧)
