### ISSUE TITLE
请问折线图是对上证50只股票进行交易的结果吗？

### ISSUE THREAD

**Issue by everydaysunny** [sunnyswag/StockRL#3]
我看到utils/models.py中对于超参数的设置为：
df = Pull_data(config.SSE_50[:2], save_data=False).pull_data()
stock_dimension = len(df.tic.unique()) # 2
state_space = 1 + 2*stock_dimension + len(config.TECHNICAL_INDICATORS_LIST)*stock_dimension # 23

感觉是加载了前两只股票的数据？那最终得到的折线图是对上证50只股票的交易结果还是对2只股票的交易结果呢？

**Comment by sunnyswag** [comment]
放在 `if __name__ == "__main__":` 中是对 `utils/models.py` 的测试，测试的过程只加载了前两只股票的数据<br>
最终得到的折线图是对上证50股票池的交易结果，可以在 [这里](https://github.com/sunnyswag/RL_in_Stock/blob/4d8a334e101ebfc3ffe9f852cdc82c7f312cba42/learn/data.py#L22) 查看到
