### ISSUE TITLE
如何应用在实盘？

### ISSUE THREAD

**Issue by chenliqiang1982** [sunnyswag/StockRL#7]
我想根据截至今天作为训练数据的所有值来预测第二天要购买的资产（即股票）
I would like to predict which asset (i.e., stock) to buy the next day based on all the values up until today as training data.
如何让模型生成第二天的买入或卖出动作？
How to make the model generate a buy or sell action for the next day?

**Comment by sunnyswag** [comment]
1. 这个可作为待完善的需求点
2. 查看回测部分的代码，你会找到答案的
