### ISSUE TITLE
关于实盘的想法。

### ISSUE THREAD

**Issue by Zero1366166516** [sunnyswag/StockRL#8]
我是刚刚下载代码，刚刚运行成功。
回来感谢一下，sunnywag!!!
是不是应该，用环境来产生预测数据，之后预测资产。

**Comment by Zero1366166516** [comment]
刚才太匆忙了，我的意思是通过环境预测新的股票价格信息，然后再用算法选择换股的策略。

**Comment by sunnyswag** [comment]
emmm，强化学习是根据当前的环境(当前及过去的股票信息)来做出具体交易决策的噢，不是预测新的股票价格信息。<br>
要预测的话，可以用 DL 的方式<br>

**Comment by Zero1366166516** [comment]
收到，我只是想看看怎么能用到实盘上。
另外我运行后，发现回测里，没有夏普率等，只有资金和收益率的报表，没有输出图形。
我是刚刚学python，刚刚给调试运行了，希望加下楼主微信，以便进一步学习。

**Comment by sunnyswag** [comment]
`夏普率等` 通过最后的回测计算出来就 OK
可以把你的联系方式发我邮箱吧~
hhq126152@gmail.com

**Comment by Zero1366166516** [comment]
已经发您邮箱了，请通过一下。

**Comment by sunnyswag** [comment]
好滴~有添加你的 wx

**Comment by linchunquan** [comment]
utils/env.py 存在明显的未来函数，还如何实盘呢？

**Comment by Zero1366166516** [comment]
您说的明显的未来函数是什么？

**Comment by linchunquan** [comment]
> 您说的明显的未来函数是什么？

https://github.com/sunnyswag/StockRL/issues/9

**Comment by Zero1366166516** [comment]
我认为T日获得T+1股价其实对算法（train）来说是没有用的，因为每天只操作一次并且T+1日的操作其实T日就已经给出了，T+1日其实是给T+2日的action。
我的问题是在T+1日时，trade的算法是怎么操作的，action的产生是否与当日（T+1）的状态相关，train和trade的机制是一样的吗？
我记得action应该是随机概率的生成，然后给定方向，根据reward调整。

**Comment by SernRounder** [comment]
> 我认为T日获得T+1股价其实对算法（train）来说是没有用的，因为每天只操作一次并且T+1日的操作其实T日就已经给出了，T+1日其实是给T+2日的action。 我的问题是在T+1日时，trade的算法是怎么操作的，action的产生是否与当日（T+1）的状态相关，train和trade的机制是一样的吗？ 我记得action应该是随机概率的生成，然后给定方向，根据reward调整。

处理action的位置确实有问题, 可以看下我在 #9 的评论, 实盘我基本上实现了, 就是在消除了未来数据后模型不再收敛...

**Comment by Zero1366166516** [comment]
收到，我详细看下，多谢！！！
